sudo: required
language: node_js
node_js:
- '7'

services:
- docker

before_script:
- npm install

script:
- docker build -t $DOCKER_REGISTRY/$HEROKU_APP/$HEROKU_APP_TYPE .

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY;
    docker push $DOCKER_REGISTRY/$HEROKU_APP/$HEROKU_APP_TYPE;
    fi

branches:
  only:
  - master

env:
  global:
    - HEROKU_APP=core-homeautomation-yan
    - HEROKU_APP_TYPE=web
    - DOCKER_REGISTRY=registry.heroku.com
    - secure: INwmjpL8zCghm0lRrLqrpiRD6XXQLbms2e3Po4imGV2zV5vFYkjfBw9tvrLo51TR6dyMGx3pSzHiMpzxL2jFPOI2/CrV0kQwImzUJUtGl/xxtlsVQIUtOtaoKqdHu+AAUB0CNB7oyer/wFj4IsSKUhZSuoesQ6NE89X7RUUe1Pq9lPvrU8i+f2io5mqfLqzcVUXfZsL6X58kZzJhuH78SNLEYNUbNHU68Vxb2fV6K0/1NB6IUdy6R5pkeWjUka4+eDNyAHVHGNqq6jTpZDImF9do0nLh34r5yit0R5NzUyy2AJJeQfx11lzRwlk0JOC1Pj9otGEuF2TaSx04Ps2gOTXqhvPewPAe/VK3uLruc2C0K4DnoUYlepca7s1RMd8McTOuqxgCyPg0Nx/as2EEejnKH6lUE+/h6R8Mmqe5WeU61YULdp2ccCCHXXf217e46GZqu8FxJ0z3KF0fRBdw0n4sCBHhnQ1w7mPk9Wnj9173spdvQIvND0I4sN4Pq+/YcjRh9WdApo6D4R0XzifjXpq+CdR0zVYQDOs4Fc2psIVa4229rKScE8uApM1oG2W07wb3DQtyZGSWVNVolS+nfuYjYeX8ZfVFPr+00qgHbANIfSMF3aHWuLY5H4H+dYWHZaPRlc4fkonQuWd+j9kzkGfQHruircV6O+29Fqbh2Gc=
    - secure: hc2YKDGnmf/RBF7Z1NuWjSPGt5fSW215PH/7xjgCoWCOxSPFig7jcjRIa+PN0oU8gZRMOk/Xo3EM/mBxJW4e6+uR8GAnvEbP9qOtiZd6gT8qFqUyLVtTiRDUiUkUdIdZ1xMtMgT5M41roT0aDXp77izLy6Box544rgVlX9ucV9FNkFKJ9/Sz5yyudEiQ6JdXJW8h9M+YnjU3JF8nrdfQag+BvoYMjQ5zSq9duVB4/kcfEzkRZESqtFlt/LO1dXQzKPj5p3ajyEs8/GNsCVj0C1v9t3ZrA6MFSXi1DuQBUeLa7jYj63cHYWjcKt6IbtlIwbQ6XA2C9xD++coD6BudihLlKmIO42t26LjNdkHsd20ImezpdZUl97fkbTRM63SYD2oQEHsiSsvS1CsV/4bFsM3+uGvTX23hF51KyMjX7mA3Y/oHV3L8ersGzm/HxPc8AOvCFoj3xfHtJptza7YRvHlPGsCBvSOuItVuVWwbFX8lP7D3YBzQU50WdTAa6G1DPTWMk+29zW/pWaWy3ed+4VZDidCg3SOH6ude2v9kQaQcV6kIWuXg363VFAbx2Ed4Is8hPJcLyNb6V5P/4hEGUYYyvJ/Fvv8Z8kUcQbbE1e1p4uk0y/y3N00mO+NKyYgQE2qvd6i20Vzbzq1sS90j0vYFiBqkFssB3pBvi6HnGKI=
